### ISSUE TITLE
Release v0.16.0

### ISSUE THREAD

**Issue by kaendfinger** [IOT-DSA/sdk-dslink-java#40]
I think it is nearing time to release v0.16.0 of the Java SDK.

Any concerns?

**Comment by Pacane** [comment]
No I'd be fine with it. I know @example6 said there was a problem with the historian and the rollups though. No clue what the problem is, and if we should wait for that to be fixed to release.

I personally think the historian will have bugs again in the future, so I wouldn't delay the release for that.
