### ISSUE TITLE
NioEventLoopGroup.shutdownGracefully isn't called

### ISSUE THREAD

**Issue by huntc** [IOT-DSA/sdk-dslink-java#92]
The SDK doesn't appear to call Netty's `NioEventLoopGroup.shutdownGracefully` method. This prevents all threads from being released upon a link provider being shutdown.

**Comment by a-hansen** [comment]
When used in broker code, NioEventLoopGroup.shutdownGracefully() is called, but not in a link. There is no need for this in the link. When a link is terminated or killed by the broker, execution ends immediately and all resources are released.  A delayed termination by using NioEventLoopGroup.shutdownGracefully() is even negative because the resources are used longer and are therefore not available for other or restarted link processes.

**Comment by huntc** [comment]
So you’re certain that all threads are terminated when a link shuts down? I think I raised this because I observed that they weren’t.

**Comment by huntc** [comment]
Incidentally, by shutting down, I don’t mean “process termination “. In approaches where many services run hosted within one JVM (to save memory), an individual service may need to stop and free all of its resources with no process termination. We operate our services in this way (similar to OSGi).
